
image: docker:stable

stage:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building application..."
    - cd ./devops/
    - python setup.py sdist
  tags:
    - production
  artifacts:
    paths:
      - dist/


test-job1:
  stage: test
  script:
    - echo "This job tests something"
  tags:
    - production

docker-stage:
  stage: deploy
  # services:
  #  - name: docker:19-dind
  #   #  entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  # #    alias: thedockerhost
  # variables:
  #   DOCKER_HOST: tcp://docker:2375/
  # #   DOCKER_DRIVER: overlay2
  # #   DOCKER_TLS_CERTDIR: ""
  script:
    - cd ./devops/
    - pip install -U twine
    - twine upload dist/* --username $PYPI_USER --password $PYPI_PASSWORDD
    # - echo "This job deploy docker image to dockerhub"
    # - docker build -t gitlab-cicd:latest .
    # - docker push atulyapandey/gitlab-cicd
  tags:
    - production